version: "3.9"
   
services:
    pgdb:
        image: postgres
        ports:
            - "5432:5432"
        container_name: pgdb
        environment:
            - POSTGRES_DB=sharity
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
    sharity:
        image: sbrkrkmz/sharity:latest
        restart: always
        container_name: sharity
        command:  /bin/sh  -c "python manage.py migrate && python manage.py loaddata db.json &&  python manage.py runserver 0.0.0.0:80 "
        ports:
            - "80:80"
        links:
            - pgdb
        depends_on:
            - pgdb

volumes:
    pgdata:

